### ISSUE TITLE
Dependecies issues

### ISSUE THREAD

**Issue by atsyplenkov** [joshualerickson/wildlandhydRo#1]
Hey, pacakge works like a charm! 
However, I had to google a bit how should I install all dependencies first. It was not straightforward since `lfstat` is hosting on R-Forge but before `lfstat` you need to install `lmomRFA`. Therefore, my successful installation path was like this:

```
install.packages("lmomRFA")
install.packages("lfstat", repos="http://R-Forge.R-project.org")
devtools::install_github("joshualerickson/wildlandhydRo")
```

Consider adding this to Readme, please

**Comment by joshualerickson** [comment]
Hey @atsyplenkov thanks for bringing this to my attention! I'll add it to the readme for sure. FWIW, this package has slowly morphed into {whitewater} and then parsing out the distribution, SNOTEL and stream stats stuff when I get some time... I'll likely put the deprecated tag on it in the near future. It was a bit ambitious when I first started and has served its purpose but I see separating out these functions will be more beneficial.

To help me understand use cases and effort into the other packages, may I ask, what were you using it for and anything you would like to see improved upon? Thanks.

**Comment by atsyplenkov** [comment]
Hi Josh,

I am afraid I am not a target audience since I am work little with US waterways. I have just used your package to quick retrieve a watershed boundaries of Ohio river. However, I am impressed with the speed, so I will explore both your packages in details in the future!

**Comment by joshualerickson** [comment]
Hey thanks! Glad it helped :). Fixed with recent [commit](https://github.com/joshualerickson/wildlandhydRo/commit/5c1061dfe986a8d1eb9da37989e535e8770d2e42).
